import mongoose from 'mongoose';
import * as dotenv from 'dotenv';
import Tour from '../models/Tour';
import Sightseeing from '../models/Sightseeing';
import Activity from '../models/Activity';
import Rental from '../models/Rental';
import Stay from '../models/Stay';
import Food from '../models/Food';
import Attraction from '../models/Attraction';

dotenv.config({ path: '.env.local' });

const MONGODB_URI = process.env.MONGODB_URI!;

async function generateSlugs() {
    if (!MONGODB_URI) {
        console.error('MONGODB_URI is not defined in .env.local');
        process.exit(1);
    }

    try {
        await mongoose.connect(MONGODB_URI);
        console.log('Connected to MongoDB');

        const models = [
            { model: Tour, name: 'Tour', field: 'title' },
            { model: Sightseeing, name: 'Sightseeing', field: 'title' },
            { model: Activity, name: 'Activity', field: 'title' },
            { model: Rental, name: 'Rental', field: 'name' },
            { model: Stay, name: 'Stay', field: 'title' },
            { model: Food, name: 'Food', field: 'title' },
            { model: Attraction, name: 'Attraction', field: 'title' }
        ];

        for (const { model, name, field } of models) {
            console.log(`Processing ${name}...`);
            const documents = await model.find({ slug: { $exists: false } });
            console.log(`Found ${documents.length} documents without slug in ${name}`);

            for (const doc of documents) {
                const title = (doc as any)[field];
                if (title) {
                    // Slug will be generated by the pre-save hook we added
                    await doc.save();
                    console.log(`Generated slug for ${name}: ${title} -> ${(doc as any).slug}`);
                }
            }
        }

        console.log('Migration completed successfully');
        process.exit(0);
    } catch (error) {
        console.error('Migration failed:', error);
        process.exit(1);
    }
}

generateSlugs();
